/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as MarketRouteImport } from './routes/market'
import { Route as ChartLabHcRouteImport } from './routes/chart-lab-hc'
import { Route as ChartLabRouteImport } from './routes/chart-lab'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StocksTickerRouteImport } from './routes/stocks.$ticker'
import { Route as SnapshotsNewRouteImport } from './routes/snapshots.new'
import { Route as SnapshotsEditRouteImport } from './routes/snapshots.edit'
import { Route as AuthKakaoCallbackRouteImport } from './routes/auth.kakao.callback'
import { Route as StocksTickerPlanPlanIdRouteImport } from './routes/stocks.$ticker_.plan.$planId'

const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartLabHcRoute = ChartLabHcRouteImport.update({
  id: '/chart-lab-hc',
  path: '/chart-lab-hc',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartLabRoute = ChartLabRouteImport.update({
  id: '/chart-lab',
  path: '/chart-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksTickerRoute = StocksTickerRouteImport.update({
  id: '/stocks/$ticker',
  path: '/stocks/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotsNewRoute = SnapshotsNewRouteImport.update({
  id: '/snapshots/new',
  path: '/snapshots/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotsEditRoute = SnapshotsEditRouteImport.update({
  id: '/snapshots/edit',
  path: '/snapshots/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthKakaoCallbackRoute = AuthKakaoCallbackRouteImport.update({
  id: '/auth/kakao/callback',
  path: '/auth/kakao/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksTickerPlanPlanIdRoute = StocksTickerPlanPlanIdRouteImport.update({
  id: '/stocks/$ticker_/plan/$planId',
  path: '/stocks/$ticker/plan/$planId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chart-lab': typeof ChartLabRoute
  '/chart-lab-hc': typeof ChartLabHcRoute
  '/market': typeof MarketRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/stats': typeof StatsRoute
  '/trends': typeof TrendsRoute
  '/snapshots/edit': typeof SnapshotsEditRoute
  '/snapshots/new': typeof SnapshotsNewRoute
  '/stocks/$ticker': typeof StocksTickerRoute
  '/auth/kakao/callback': typeof AuthKakaoCallbackRoute
  '/stocks/$ticker/plan/$planId': typeof StocksTickerPlanPlanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chart-lab': typeof ChartLabRoute
  '/chart-lab-hc': typeof ChartLabHcRoute
  '/market': typeof MarketRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/stats': typeof StatsRoute
  '/trends': typeof TrendsRoute
  '/snapshots/edit': typeof SnapshotsEditRoute
  '/snapshots/new': typeof SnapshotsNewRoute
  '/stocks/$ticker': typeof StocksTickerRoute
  '/auth/kakao/callback': typeof AuthKakaoCallbackRoute
  '/stocks/$ticker/plan/$planId': typeof StocksTickerPlanPlanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chart-lab': typeof ChartLabRoute
  '/chart-lab-hc': typeof ChartLabHcRoute
  '/market': typeof MarketRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/stats': typeof StatsRoute
  '/trends': typeof TrendsRoute
  '/snapshots/edit': typeof SnapshotsEditRoute
  '/snapshots/new': typeof SnapshotsNewRoute
  '/stocks/$ticker': typeof StocksTickerRoute
  '/auth/kakao/callback': typeof AuthKakaoCallbackRoute
  '/stocks/$ticker_/plan/$planId': typeof StocksTickerPlanPlanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chart-lab'
    | '/chart-lab-hc'
    | '/market'
    | '/plans'
    | '/profile'
    | '/search'
    | '/stats'
    | '/trends'
    | '/snapshots/edit'
    | '/snapshots/new'
    | '/stocks/$ticker'
    | '/auth/kakao/callback'
    | '/stocks/$ticker/plan/$planId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chart-lab'
    | '/chart-lab-hc'
    | '/market'
    | '/plans'
    | '/profile'
    | '/search'
    | '/stats'
    | '/trends'
    | '/snapshots/edit'
    | '/snapshots/new'
    | '/stocks/$ticker'
    | '/auth/kakao/callback'
    | '/stocks/$ticker/plan/$planId'
  id:
    | '__root__'
    | '/'
    | '/chart-lab'
    | '/chart-lab-hc'
    | '/market'
    | '/plans'
    | '/profile'
    | '/search'
    | '/stats'
    | '/trends'
    | '/snapshots/edit'
    | '/snapshots/new'
    | '/stocks/$ticker'
    | '/auth/kakao/callback'
    | '/stocks/$ticker_/plan/$planId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChartLabRoute: typeof ChartLabRoute
  ChartLabHcRoute: typeof ChartLabHcRoute
  MarketRoute: typeof MarketRoute
  PlansRoute: typeof PlansRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  StatsRoute: typeof StatsRoute
  TrendsRoute: typeof TrendsRoute
  SnapshotsEditRoute: typeof SnapshotsEditRoute
  SnapshotsNewRoute: typeof SnapshotsNewRoute
  StocksTickerRoute: typeof StocksTickerRoute
  AuthKakaoCallbackRoute: typeof AuthKakaoCallbackRoute
  StocksTickerPlanPlanIdRoute: typeof StocksTickerPlanPlanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart-lab-hc': {
      id: '/chart-lab-hc'
      path: '/chart-lab-hc'
      fullPath: '/chart-lab-hc'
      preLoaderRoute: typeof ChartLabHcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart-lab': {
      id: '/chart-lab'
      path: '/chart-lab'
      fullPath: '/chart-lab'
      preLoaderRoute: typeof ChartLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/$ticker': {
      id: '/stocks/$ticker'
      path: '/stocks/$ticker'
      fullPath: '/stocks/$ticker'
      preLoaderRoute: typeof StocksTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshots/new': {
      id: '/snapshots/new'
      path: '/snapshots/new'
      fullPath: '/snapshots/new'
      preLoaderRoute: typeof SnapshotsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshots/edit': {
      id: '/snapshots/edit'
      path: '/snapshots/edit'
      fullPath: '/snapshots/edit'
      preLoaderRoute: typeof SnapshotsEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/kakao/callback': {
      id: '/auth/kakao/callback'
      path: '/auth/kakao/callback'
      fullPath: '/auth/kakao/callback'
      preLoaderRoute: typeof AuthKakaoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/$ticker_/plan/$planId': {
      id: '/stocks/$ticker_/plan/$planId'
      path: '/stocks/$ticker/plan/$planId'
      fullPath: '/stocks/$ticker/plan/$planId'
      preLoaderRoute: typeof StocksTickerPlanPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChartLabRoute: ChartLabRoute,
  ChartLabHcRoute: ChartLabHcRoute,
  MarketRoute: MarketRoute,
  PlansRoute: PlansRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  StatsRoute: StatsRoute,
  TrendsRoute: TrendsRoute,
  SnapshotsEditRoute: SnapshotsEditRoute,
  SnapshotsNewRoute: SnapshotsNewRoute,
  StocksTickerRoute: StocksTickerRoute,
  AuthKakaoCallbackRoute: AuthKakaoCallbackRoute,
  StocksTickerPlanPlanIdRoute: StocksTickerPlanPlanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
